In [2]:
import numpy as np
import cv2

In [10]:
face_cascade = cv2.CascadeClassifier('C:/Python27/Lib/site-packages/opencv/sources/data/haarcascades/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('C:/Python27/Lib/site-packages/opencv/sources/data/haarcascades/haarcascade_eye.xml')
img = cv2.imread('C:/Users/pradeepsingh.naulia/OneDrive - Xchanging/comp vision CV/WIN_20170307_16_33_46_Pro.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [30]:
gray

array([[203, 208, 190, ..., 188, 189, 186],
       [138, 136, 129, ..., 190, 191, 188],
       [101,  95, 107, ..., 189, 189, 187],
       ..., 
       [ 28,  29,  29, ...,  60,  54,  59],
       [ 28,  31,  35, ...,  56,  53,  60],
       [ 39,  43,  43, ...,  67,  60,  61]], dtype=uint8)

In [45]:
face_cascade

<CascadeClassifier 00000000040C8AF0>

In [4]:
img = cv2.imread('C:/Users/pradeepsingh.naulia/OneDrive - Xchanging/comp vision CV/rightportrait.jpg')
print img

[[[140 182 189]
  [138 180 187]
  [135 177 184]
  ..., 
  [209 239 244]
  [209 239 244]
  [210 240 245]]

 [[143 185 192]
  [144 186 193]
  [142 184 191]
  ..., 
  [209 239 244]
  [209 239 244]
  [210 240 245]]

 [[144 186 193]
  [145 187 194]
  [142 184 191]
  ..., 
  [210 240 245]
  [209 239 244]
  [209 239 244]]

 ..., 
 [[ 26  30  78]
  [ 29  33  81]
  [ 35  39  87]
  ..., 
  [124 147 179]
  [123 146 178]
  [125 148 180]]

 [[ 28  32  80]
  [ 24  28  76]
  [ 24  28  76]
  ..., 
  [126 149 181]
  [125 148 180]
  [127 150 182]]

 [[ 33  37  85]
  [ 25  29  77]
  [ 25  29  77]
  ..., 
  [125 148 180]
  [123 146 178]
  [123 146 178]]]


In [11]:
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()